### ISSUE TITLE
It seems that it is impossible to get matter infused production science pack in normal game

### ISSUE THREAD

**Issue by IlK7** [AlienXAXS/AXMatter#1]
To make Matter production science powder, you need cracked matter, that you can get by getting a centrifuge that requires matter production science powder to research, so I don't see any way to get matter infused production science. It seems to be a typo, because centrifuge tech requires matter infused blue science pack tech, while all other techs, that require matter production science packs, require the tech to produce matter production science packs. I show the issue in images below
![prb1](https://user-images.githubusercontent.com/57229224/67964738-6d4a4580-fc09-11e9-8cee-e2b52a5a906e.png)
![prb2](https://user-images.githubusercontent.com/57229224/67964739-6de2dc00-fc09-11e9-8b17-beedd5a408b0.png)

**Comment by AlienXAXS** [comment]
Hi buddy,
Yeah i heard about this a little bit ago - a massive oopsie from my end.

Will submit a fix shortly :)

**Comment by AlienXAXS** [comment]
All fixed, new version released.
Please note, that AiX Matter has not had any proper updates in a long while, so you might find other bugs :)

**Comment by IlK7** [comment]
thanks!
